# Development Environment Configuration
# Used by GitHub Actions workflow for dev deployments

name: Development Environment

# AWS Configuration
aws:
  region: us-east-1

# Environment Settings
environment:
  name: dev
  stack_name: insightmodai-agent-dev

# CloudFormation Parameters
cloudformation:
  parameters:
    AdminEmail: dev-admin@yourcompany.com
    BedrockModelId: us.anthropic.claude-3-5-sonnet-20241022-v2:0
    EnvironmentName: dev
    EnableCRM: false

# Application Configuration
app:
  log_level: DEBUG
  enable_debug_logs: true

# Resource Configuration (Development - Cost Optimized)
resources:
  lambda:
    memory_size: 512
    timeout: 300
  dynamodb:
    billing_mode: PAY_PER_REQUEST
  cloudwatch:
    log_retention_days: 7
    enable_alarms: false

# Security Configuration
security:
  cognito:
    mfa_configuration: OFF

# Deployment Configuration
deployment:
  auto_deploy: true
  create_github_release: false
  require_approval: false
